use_frameworks!

target 'PanelController_Example' do
  pod 'PanelController', :path => '../'
end

target 'PanelController_Tests' do
  pod 'PanelController', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
