use_frameworks!

target 'PanelController_Example' do
  pod 'PanelController', :path => '../'
end

target 'PanelController_Tests' do
  pod 'PanelController', :path => '../'

  pod 'Quick'
  pod 'Nimble'
end
